import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landingPage/Navbar";
import Footer from "@/components/landingPage/Footer";


const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Navbar />
        <main className="max-w-8xl mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
